version: '3.8'

services:
  web:
    build:
      context: .
    container_name: papelaria-django-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - .:/app
    networks:
      - backend
    entrypoint: ["/bin/sh", "-c", "chmod +x /app/scripts/entrypoint.sh && /app/scripts/entrypoint.sh"]

  db:
    image: postgres
    container_name: papelaria-postgres-database
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
