# Generated by Django 4.0.4 on 2022-12-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['week_day']},
        ),
        migrations.RemoveField(
            model_name='commission',
            name='active',
        ),
        migrations.AlterField(
            model_name='commission',
            name='commission_max',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='commission',
            name='commission_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commission',
            name='week_day',
            field=models.PositiveIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at', None)), fields=('week_day',), name='unique_week_day_if_not_deleted'),
        ),
    ]
