# Generated by Django 4.0.4 on 2022-11-28 01:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('employee', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('commission_min', models.PositiveIntegerField()),
                ('invoice', models.CharField(max_length=128)),
                ('client', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('employee', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('sale', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='sale.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
