# Generated by Django 4.0.4 on 2022-11-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='commission_max',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='commission_min',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
